# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      # For Qt
      - libegl1-mesa-dev

      # For ogles_gpgpu (GL library)
      - libgl1-mesa-dev

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      - g++-5
      - gcc-5

      - clang-5.0
      - libc++-dev
      - libc++abi-dev
      - libclang-5.0-dev
      - libclang-common-5.0-dev
      - libclang1-5.0

      # pip3
      - python3-pip

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=libcxx-fpic-hid-sections INSTALL=--strip

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc-5-pic-hid-sections-lto INSTALL=--strip

    # }

    # OSX {

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12-hid-sections INSTALL=--install

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=MinSizeRel TOOLCHAIN=ios-nocodesign-10-3-arm64-dep-9-0-device-libcxx-hid-sections INSTALL=--install

    - os: osx
      osx_image: xcode8.3
      env: CONFIG=Release TOOLCHAIN=osx-10-12-sanitize-address-hid-sections INSTALL=--install

    - os: osx
      env: CONFIG=MinSizeRel TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections INSTALL=--strip

    # }

env:
  global:
    - secure: "copxh/FOt+cC3TohV8GLrqmxJl/C45uNHt0hbY6E4GAw2yo4AAO5lPpGv2f/9lvxpHFv/n/mZu5MmlJwn5nJrDAb3K6r7pC5jFR0o8MFfUu+dfCm6tR0tWzFPuTuQTjnMl4wmM+t72KI7NHk0HvHm51tlR6J8Vz+OGIvt9vVHBAQtWFs9CbdiGl/HT+kjzw97xpYvbNImDsEOTYBMJExTmx+8s3MmhOyUDmbJO1x5XRF1C9CX2RALBwJbNz0oOI8FFChmtzUKzErvy5JWy8zvwWq/oQKl42RFi9GRLFM5+3NdHP8gXARykJp32cdBdtR1Sih6ySGOjrtT2go/y/asj7r2eXqewKLPsnbddeoovl098kATy/e3A1F9qZSGGMDtrW1xTaRG77KdbSXrQvnXKB58IjpDU5gCwwVFs2hbldjwsFsgcQ4w/RAHhvQrYy7S0lcqa+OjXjeYLn9DNjrZNm89Q99XbGFKCAitEcAfvG1IPsWvl4518bjBE7qwK4sUG7GFstFCGmTzy7ZhBz9vBTe7/SKu/8fYMOVmhX77rLFazZGcc6cOzoTIGdMWU2narwjAuzN7c3NzchcUtC13/+MhWgr/TLMqWJmhPHmwLMt6xrqM+DfEQzv1RFbH1t5WSnfa1L3DKgC2SW84lmL5cQScZ/qvsJC2xEpIrp49xQ="

# disable the default submodule logic to support local modification of .gitmodules paths
git:
  submodules: false

# See https://docs.travis-ci.com/user/private-dependencies/#API-Token
# CI_USER_TOKEN is added to .travis.yml settings
before_install:

  # Add '--quiet' to avoid leaking the token to logs
  - git submodule update --init --recursive --quiet

  # https://stackoverflow.com/a/38790045
  - bin/travis_clang_links.sh

install:
  - source bin/hunter_env.sh

script:
  - bin/travis_build.sh "${TOOLCHAIN}" "${CONFIG}" "${INSTALL}"

before_deploy:
    - gem install mime-types -v 2.6.2 # workaround for https://github.com/travis-ci/travis-ci/issues/5145
    - export FILE_TO_UPLOAD=$(ls _archives/acf-*.tar.gz)

deploy:
  provider: releases
  api_key:
    - secure: "LqSdaNS6LyKpgJX3J6Fm7Tgf9cYRF1Uz9mH0oOEdgYdJd1XVPsHpvihgm+ItznlsKxU1Rgg5+b5YzDX4g3NJSA9GXAbBz+1jczeGZvLTgJOo07u4i0Ze4/8b1fXw/Maz+I7DVD6pWyDWgoe1Wh70BKhqn1DjX0C69bIyW+uBABVAjFPG2xSsfZ0Z0hG24H8yC3VJom77MeFvrNhWNeeN5ap23s2gzkm8bJMXd5NkTZ0/XLVTD3biD5WhOVDLHjeZETz83yDY3sdjBWRR2M68jtXZTqvU0nt9tgNCzATeAhklUF80Vh0VDv9QXNSLtmtRBiQcmfcL9S+hRyztW0xnC/PUNGh0xOYZ7w8PnD1EbT//neF1oyByMpCv1W/keRg4qCBnZdDc6s6PaNqkNvsqE5KWi6+sAYukaWnpyScFquvx2YTSOeBtyl3Tivj9AYvReB/ooZS5skNjt0F+qdmriodpDj4uvrii8ggF0Qn8fkzhhXslMIjNONiDi8ATDZH+V76fkyqG0fLZJtjBKA8DHKPrCh9CSRHs75Lwzx0lnunlL5lyLH/ZnSgY7d7q491F2auF90c4KbeS6aRL+ivDZDMPvVMZtSGvAfvWmVTM+uIsIaIHmk60Z2xoseaInIST2nKWHwSplCkA+yBhiCPA+WYJWxqB5MOChQxxLAopSFs="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^pr\..*/
